### ISSUE TITLE
Similar inputs, different outputs

### ISSUE THREAD

**Issue by XPnJt8s7** [bmhm/sig2dot2#2]
These two outputs of `gpg` don't give the same results:

`tru::1:1540649360:0:3:1:5
pub:u:3072:1:3297B9A9525048B0:1540401548:::u:::scESC::::::23::0:
fpr:::::::::048ABB8F6F25392C986F8C193297B9A9525048B0:
uid:u::::1540401548::60938821A935E5AFEBDB06E1724A2AC898AC9407::Homer <homes@springfield.com>::::::::::0:
sig:::1:3297B9A9525048B0:1540401548::::Homer <homes@springfield.com>:13x:::::10:
sub:u:3072:1:58936B06AB139740:1540401548::::::e::::::23:
fpr:::::::::7FDBC5014FCFD0FE7505D21458936B06AB139740:
sig:::1:3297B9A9525048B0:1540401548::::Homer <homes@springfield.com>:18x:::::10:
pub:f:3072:1:77B3E98C6E2D9B2B:1540396571:::-:::scESC::::::23::0:
fpr:::::::::DB638856C6023172EB91D6DB77B3E98C6E2D9B2B:
uid:f::::1540396571::F9675C33E4FFB92EC3E51183E202769D646660EC::Bart <bart@springfield.com>::::::::::0:
sig:::1:77B3E98C6E2D9B2B:1540396571::::Bart <bart@springfield.com>:13x:::::10:
sig:::1:16EF36EAC0B63568:1540404621::::Lisa <Lisa@springfield.com>:10x:::::10:
sub:f:3072:1:76AD64A838FB6D5E:1540396571::::::e::::::23:
fpr:::::::::A16B5639140F63FF4DBBE56C76AD64A838FB6D5E:
sig:::1:77B3E98C6E2D9B2B:1540396571::::Bart <bart@springfield.com>:18x:::::10:
pub:f:3072:1:16EF36EAC0B63568:1540396179:::f:::scESC::::::23::0:
fpr:::::::::D395BB4C7C27F5C9837D5AA616EF36EAC0B63568:
uid:f::::1540396179::D1AEE74F15D4505999945B2306DDAEBAB384CEED::Lisa <Lisa@springfield.com>::::::::::0:
sig:::1:16EF36EAC0B63568:1540396179::::Lisa <Lisa@springfield.com>:13x:::::10:
sig:::1:3297B9A9525048B0:1540406655::::Homer <homes@springfield.com>:10x:::::10:
sub:f:3072:1:BB9AB8B892312CEA:1540396179::::::e::::::23:
fpr:::::::::EB9E0B6C7DB6F1DD1A1B9AC0BB9AB8B892312CEA:
sig:::1:16EF36EAC0B63568:1540396179::::Lisa <Lisa@springfield.com>:18x:::::10:
`

`tru::1:1540651051:0:3:1:5
pub:u:3072:1:07CBF2B2E5C18D06:1540650040:::u:::scESC::::::23::0:
fpr:::::::::82EC685F6E1AD1C0178D3C9707CBF2B2E5C18D06:
uid:u::::1540650040::A0163868A119FA4E2F673972A1C86FAC085829AD::Gabriel <gabriel@mail.fr>::::::::::0:
sig:::1:07CBF2B2E5C18D06:1540650040::::Gabriel <gabriel@mail.fr>:13x:::::10:
sub:u:3072:1:A8ED08E09B7F900A:1540650040::::::e::::::23:
fpr:::::::::A31DCF7BB3A9AFF14F86CF80A8ED08E09B7F900A:
sig:::1:07CBF2B2E5C18D06:1540650040::::Gabriel <gabriel@mail.fr>:18x:::::10:
pub:f:3072:1:399D52DF21EC0AC2:1540645949:::-:::scESC::::::23::0:
fpr:::::::::A69737342879BF215B26A974399D52DF21EC0AC2:
uid:f::::1540645949::4413EB8537DA2B4974A6168D37629988C5FA6E1B::Emma M <emma@mail.fr>::::::::::0:
sig:::1:399D52DF21EC0AC2:1540645949::::Emma M <emma@mail.fr>:13x:::::10:
sig:::1:D8B4A0066531477A:1540650651::::Jules <jules@mail.fr>:10x:::::10:
sub:f:3072:1:C96E37855671E20E:1540645949::::::e::::::23:
fpr:::::::::382FAD3FD662A00D6F61C43AC96E37855671E20E:
sig:::1:399D52DF21EC0AC2:1540645949::::Emma M <emma@mail.fr>:18x:::::10:
pub:f:3072:1:D8B4A0066531477A:1540650403:::f:::scESC::::::23::0:
fpr:::::::::34C62289A41071FF0BE28E66D8B4A0066531477A:
uid:f::::1540650403::F9D6792F2F09158A960883931D357606DAC30111::Jules <jules@mail.fr>::::::::::0:
sig:::1:D8B4A0066531477A:1540650403::::Jules <jules@mail.fr>:13x:::::10:
sig:::1:07CBF2B2E5C18D06:1540650810::::Gabriel <gabriel@mail.fr>:10x:::::10:
sub:f:3072:1:A60439E5F782475C:1540650403::::::e::::::23:
fpr:::::::::EB786CE65BC73555888348C5A60439E5F782475C:
sig:::1:D8B4A0066531477A:1540650403::::Jules <jules@mail.fr>:18x:::::10:
`

Even creating the `ps` from each account, the one of Gabriel won't show the arrows.

![1_gabriel](https://user-images.githubusercontent.com/33459397/47605952-5af16680-da0d-11e8-9d45-9cbc2ba927ca.png)
![ps](https://user-images.githubusercontent.com/33459397/47605953-5af16680-da0d-11e8-9cae-ea25e4de3a09.png)

**Comment by XPnJt8s7** [comment]
The two first were generated with `dot`. With neato `neato` :
![1_gabriel2222](https://user-images.githubusercontent.com/33459397/47606002-17e3c300-da0e-11e8-981d-91481ab4ed4d.png)
![ps](https://user-images.githubusercontent.com/33459397/47606003-17e3c300-da0e-11e8-9bff-e81c893d0602.png)

**Comment by XPnJt8s7** [comment]
Dot files :

https://pastebin.com/EEzGM4ud

**Comment by bmhm** [comment]
Thank you for this information!
Sadly, this project is abandoned. If you'd like to get commit rights to this repository, just tell me.

**Comment by paalbra** [comment]
@XPnJt8s7 I just ran sig2dot with your example input and I get the expected relations: Gabriel -> Jules -> Emma M.

I've done a quick read through of the code (first time) and there are some code that will behave differently based on timestamps. My guess is that the Gabriel-Jules-EmmaM signatures where considered to be in the future when you drew the dot-graph:
https://github.com/bmhm/sig2dot2/blob/master/sig2dot/exporter/dot/writer.py#L92-L94

Your comments here on github are on the same day as the timestamps in the example and this strengthens my suspicion.

There might of course be a bug here though. Maybe some rounding of dates/timestamps occur and a close past timestamp will be considered to be in the future.

**Comment by paalbra** [comment]
Ah yeah. The "rendertime" is set to `date.today().isoformat()`, which is the current day at 00:00. This means that any signature signed that same day will be considered to be in the future and will not be drawn.

**Comment by paalbra** [comment]
@bmhm Do you take pull requests or do you not want to manage this repo anymore?

I enjoy graphing stuff myself and might look into fixing this issue and others if there are any (I would need to read through the code some more).

**Comment by bmhm** [comment]
Hey paalbra,

I'm coding python anymore, I'm a java EE coder vor many years now. You can either take over (or just fork) this repo, if this code is still good enough. Nevertheless, personally I'd rewrite it (like: creating more objects with more information).
I'll add you as contributor for now, so you can merge stuff yourself. :-)

**Comment by paalbra** [comment]
@bmhm I understand. I'll fix this issue when I have some time to spare and will look into the other parts of the code as well :)
